freebsd_instance:
  image: freebsd-12-1-release-amd64

freebsd_task:
  install_script:
    - uname -a
    - "pkg install -y check cyrus-sasl gcc gmake pkgconf protobuf protobuf-c"
  test_script:
    - uname -a
    - gmake -j$(sysctl -n hw.ncpu) all

# only_if feature seems to be broken, at least on FreeBSD, or documented
# incorrectly :/.  The environment variable is populated during scripts, but
# does not appear to exist globally in tasks.
#only_if: $CIRRUS_OS == freebsd
