dist: xenial
language: c
compiler: gcc
addons:
  apt:
    packages:
      - protobuf-c-compiler
      - libprotobuf-c-dev
      - libprotobuf-c1
      - libsasl2-dev
      - libsasl2-2
      - check

# TODO:
# make test requires live HDFS cluster...
# For now, just compile everything.
script: >
  make WARNS_NEW= all
