dist: xenial
language: c
compiler: gcc
addons:
  apt:
    packages:
      - protobuf-c-compiler
      - libprotobuf-c-dev
      - libprotobuf-c1
      - libsasl2-dev
      - libsasl2-2
      - check
env:
  global:
    CK_VERBOSITY: verbose
    HDFS_TEST_NODE_ADDRESS: localhost

# TODO:
# make test requires live HDFS cluster...
# For now only run the unit suite which doesn't deal directly with HDFS
script:
  - make -j$(nproc) WARNS_NEW= all
  - env CK_RUN_SUITE=unit make test
